site_name: ElectroBlocks
nav:
  - Home: index.md
  - What is an Arduino?: what-is-an-arduino.md
  - Setting up Chrome: setting-up-chrome.md
  - Blink: blink.md
  - Messages: messages.md
  - Servos: servos.md
  - RGB LED: rgbled.md
  - NeoPixels: neopixel.md
theme:
  name: readthedocs
extra_css:
  - css/style.css
