site_name: ElectroBlocks
nav:
  - Home: index.md
  - What is an Arduino?: what-is-an-arduino.md
  - Blink: blink.md
  - Variables: variables.md
  - Servos: servos.md
theme:
  name: readthedocs
extra_css:
  - css/style.css
