site_name: ElectroBlocks
nav:
  - Getting Started: index.md
  - Blocks: blocks.md
  - Addons: addons.md
  - ElectroBlocks Lessons:
      - What is an Arduino?: lessons/what-is-an-arduino.md
      - Blink: lessons/blink.md
      - HighFive Machine: lessons/highfive.md
      - Wave Machine: lessons/wave.md
  - How Tos:
      - Save Project: howto/saveproject.md
      - Open Project: howto/openproject.md
theme:
  name: readthedocs
extra_css:
  - css/style.css
