site_name: ElectroBlocks
nav:
  - Getting Started: index.md
  - Blocks: blocks.md
  - Addons: addons.md
  - ElectroBlocks Lessons:
      - What is an Arduino?: lessons/what-is-an-arduino.md
      - Blink: lessons/blink.md
      - Sending Messages: lessons/sending-messages.md
      - HighFive Machine: lessons/highfive.md
      - Wave Machine: lessons/wave.md
      - RGB LED: lessons/rgbled.md
      - RGB LED Light Strip: lessons/fastled.md
      - Motion Sensor RGB LED Light Strip: lessons/sonar-motion-sensor.md
      - Flappy Bird: lessons/flappybird.md
  - How Tos:
      - Save Project: howto/saveproject.md
      - Open Project: howto/openproject.md
theme:
  name: readthedocs
extra_css:
  - css/style.css
